#pragma once

#include "kernel.h"

namespace esse {
	namespace constructor {
		ENGINE_REFLECTED_CLASS(IncludePath, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, path);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(Configuration, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, name); // Mac, Win32
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, includePath);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, defines);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, macFrameworkPath);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, windowsSdkVersion);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, compilerPath);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, cStandard);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, cppStandard);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, intelliSenseMode);
			ENGINE_DEFINE_REFLECTED_GENERIC_PROPERTY(IncludePath, browse);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(Configurations, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_GENERIC_SAFE_ARRAY(Configuration, configurations);
			ENGINE_DEFINE_REFLECTED_PROPERTY(INTEGER, version); // 4
		ENGINE_END_REFLECTED_CLASS

		ENGINE_REFLECTED_CLASS(BuildTaskGroup, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, kind);
			ENGINE_DEFINE_REFLECTED_PROPERTY(BOOLEAN, isDefault);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(BuildTask, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, label);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, type);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, command);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, args);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, problemMatcher);
			ENGINE_DEFINE_REFLECTED_GENERIC_PROPERTY(BuildTaskGroup, group);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(BuildTasks, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_GENERIC_SAFE_ARRAY(BuildTask, tasks);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, version); // "2.0.0"
		ENGINE_END_REFLECTED_CLASS

		ENGINE_REFLECTED_CLASS(LaunchTask, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, name);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, type);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, request);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, program);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, args);
			ENGINE_DEFINE_REFLECTED_PROPERTY(BOOLEAN, stopAtEntry);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, cwd);
			ENGINE_DEFINE_REFLECTED_PROPERTY(BOOLEAN, externalConsole);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, MIMode);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(LaunchList, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_GENERIC_SAFE_ARRAY(LaunchTask, configurations);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, version); // "0.2.0"
		ENGINE_END_REFLECTED_CLASS

		bool make_development_environment(build_state & build, bool make_environment, bool make_workspace);
	}
}